### ISSUE TITLE
Add an option to disable `omitempty`

### ISSUE THREAD

**Issue by ayoubfaouzi** [whosydd/go-tags#1]
Hey @whosydd 

Great extension ! A life saver.

I was wondering if you can add an option in the settings that can skip the addition of the omitempty.

Cheers.

**Comment by whosydd** [comment]
Sorry, I don't understand what you mean, currently extension functions do not involve omitempty.

If possible, please describe your needs in detail.

**Comment by ayoubfaouzi** [comment]
When I generated the tags for my struct, it adds omitempty automatically, which I would like to avoid.

Before:

```go
type ImageLoadConfigDirectory struct {
	Size          uint32
	TimeDateStamp uint32
	Major         uint32
}
```
After:
```go
type ImageLoadConfigDirectory struct {
	Size          uint32 `json:"size,omitempty"`
	TimeDateStamp uint32 `json:"time_date_stamp,omitempty"`
	Major         uint32 `json:"major,omitempty"`
}
```

**Comment by ayoubfaouzi** [comment]
Sorry, I think I was using an option in vscode that maybe does not come from your extension:

![image](https://user-images.githubusercontent.com/5129564/219614873-485df71d-5596-45ab-ad90-12762b2b67b7.png)

Apologies, my bad.
